### PR TITLE
Merging #33

### PR DESCRIPTION
**Pull request by mrkn**
In this pull-request, I want to merge @toddsundsted's works for implementation of Gluon based on my work-in-progress code base.

### CODE REVIEW

**Comment by toddsundsted** [comment]
@mrkn if i can make any changes to my code to make the merge easier, just let me know!

**Comment by mrkn** [comment]
@toddsundsted Thank you for your kindness.  I'll ask you to change something if I need.

**Comment by mrkn** [comment]
@toddsundsted I marked the examples I cannot fix in this PR as pending.

The remaining work is fixing for passing CI only.  I'll merge this PR after that.

**Comment by toddsundsted** [comment]
@mrkn I'm fine with leaving adf9d7c out. generally I prefer consistency with Python, as well -- I just couldn't resist trying to fix the bad design here...

**Comment by toddsundsted** [comment]
woohoo!

**Pull request merged**
